### ISSUE TITLE
Refreshes only first time after opening PBI Desktop

### ISSUE THREAD

**Issue by rquintino** [djouallah/PowerBI_Desktop_Refresh#1]
Hi Mimoune, was testing the script, noticed it refreshes only first time after opening PBI
Did you experience the same?
(tested sources R/CSV, refreshes ok but have to open each time for it to work)
thanks!

**Comment by djouallah** [comment]
yeah you need PBD to be open in order to works, 
PBD desktop launch an instance of SSAS, when you close PBD, the SSAS close, so we can not refresh if PBD is closed, is that your question

**Comment by rquintino** [comment]
hi, not exactly,
my issue is that it only refreshes first time after opening PBI, if I skip the pbi open command, it won't throw error, but won't update

ex: rerun with these commented, 
#START-PROCESS $PBIDesktop $template | Out-Null
#Start-Sleep -s $waitoPBD

won't refresh (testing with R Sys.time or changing a local csv)

**Comment by djouallah** [comment]
although the local SSAS is refreshed with the latest data, the changes are not saved in the PBIX file (which is zipped *.abf plus metadata and reports), and the reports show the old data, which give the impression that the refresh did not work, if you want to save the changes, you need to click save on the PowerBI Desktop I don't know how to trigger PowerBI desktop to refresh the view of the data in SSAS refreshed by external means
 Please there is no guaranty whatever, always make a copy of your pbix before doing anything

**Comment by djouallah** [comment]
i think all we can do is vote on this idea and hope Microsoft listen

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/7345565-power-bi-designer-api
